# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.01.24
_src_path: gh:scientific-python/cookie
backend: hatch
email: c.dacostaf@gmail.com
full_name: Carlos Alberto da Costa Filho
license: MIT
org: cako
project_name: Curvelets
project_short_description: Python package for curvelet transforms.
url: https://github.com/cako/curvelets
vcs: true
