r"""
Curvelet-Domain Hessian Action
==============================

This example showcases how the curvelet transform can be used to estimate and
compensate for the action of the Hessian in Least-Squares Migration (LSM), inspired by
:cite:t:`Wang2016,Wang2017`.

Let :math:`F(m)` represent the non-linear full forward modeling operator and :math:`J = \frac{\partial F}{\partial m}`
denote the Born modeling operator (the Jacobian). The Gauss-Newton Hessian is given by
:math:`H_{gn} = J^\dagger J`. The Full Newton Hessian :math:`H_{fn} = F^\dagger F` includes additional second-order
terms to represent the full local curvature.

The Gauss-Newton Hessian :math:`H_{gn}` acts as a spatially varying, directionally
dependent blurring operator (a dip filter). By analyzing the Hessian-vector product
on a point scatterer (which acts as a Point Spread Function), we can see that the
blurring is highly anisotropic.

The curvelet transform, which localizes signals in both position and direction,
is perfectly suited to diagonalize this operator. In the curvelet domain, the Hessian
acts approximately as a scalar multiplier on each coefficient, allowing us to build
a Curvelet-domain Hessian Filter (CHF) to invert it.

In this tutorial, we will:

#. Visualize the anisotropic blurring effect of the Gauss-Newton and Full Newton Hessians on a grid of point scatterers.

#. Analyze how this blurring is represented by curvelet coefficients across different scales and angles.

#. Build and apply a localized Curvelet-domain Hessian Filter (CHF) using overlapping patches to recover the true scatterers from the blurred gradient.
"""

# sphinx_gallery_thumbnail_number = 2

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pylops
from scipy.ndimage import gaussian_filter

from curvelets.numpy import UDCT
from curvelets.plot import create_colorbar, despine

# %%
# Load the Hessian-Vector Product Workspace
# -----------------------------------------
# We load a pre-computed workspace generated by a migration experiment. It contains:
#
# - :math:`\delta m`: A grid of point scatterers (the true model).
# - :math:`g`: The gradient or migrated image (:math:`J^\dagger \delta d`), where :math:`J` is the Born modeling operator (Jacobian).
# - :math:`h_{gn}`: The action of the Gauss-Newton Hessian on the gradient (:math:`J^\dagger J g`).
# - :math:`h_{full}`: The action of the Full Newton Hessian (:math:`H_{fn}`) on the gradient (:math:`H_{fn} g`).

workspace_path = Path("testdata/hessian_workspace.npz")
if not workspace_path.exists():
    workspace_path = Path("../testdata/hessian_workspace.npz")
if not workspace_path.exists():
    msg = "Could not find hessian_workspace.npz. Please generate it first."
    raise FileNotFoundError(msg)

data = np.load(workspace_path)
dm = data["dm"]
grad = data["grad"]
h_gn = data["h_gn_grad"]
h_full = data["h_full_grad"]
dx, dy = data["dx"], data["dy"]

# Crop to even dimensions for the transform
dm = dm[:-1, :-1]
grad = grad[:-1, :-1]
h_gn = h_gn[:-1, :-1]
h_full = h_full[:-1, :-1]

print(f"Loaded workspace with shape {dm.shape}")

dimsd = grad.shape
slice_x = slice(100, 260)
slice_z = slice(100, 200)

dm_c = dm[slice_x, slice_z]
grad_c = grad[slice_x, slice_z]
h_gn_c = h_gn[slice_x, slice_z]
h_full_c = h_full[slice_x, slice_z]

fig1, axs1 = plt.subplots(3, 2, figsize=(10, 15))
opts = {"cmap": "RdBu_r", "aspect": "equal"}
pclip = 0.5

im0 = axs1[0, 0].imshow(
    dm_c.T, vmin=-pclip * np.abs(dm_c).max(), vmax=pclip * np.abs(dm_c).max(), **opts
)
axs1[0, 0].set_title("1) True Scatterer ($\\delta m$)")
create_colorbar(im0, ax=axs1[0, 0])

im1 = axs1[0, 1].imshow(
    grad_c.T,
    vmin=-pclip * np.abs(grad_c).max(),
    vmax=pclip * np.abs(grad_c).max(),
    **opts,
)
axs1[0, 1].set_title("2) Gradient ($g = J^\\dagger \\delta d$)")
create_colorbar(im1, ax=axs1[0, 1])

im2 = axs1[1, 0].imshow(
    h_gn_c.T,
    vmin=-pclip * np.abs(h_gn_c).max(),
    vmax=pclip * np.abs(h_gn_c).max(),
    **opts,
)
axs1[1, 0].set_title("3) GN Hessian on Gradient ($H_{gn} g$)")
create_colorbar(im2, ax=axs1[1, 0])

im3 = axs1[1, 1].imshow(
    h_full_c.T,
    vmin=-pclip * np.abs(h_full_c).max(),
    vmax=pclip * np.abs(h_full_c).max(),
    **opts,
)
axs1[1, 1].set_title("4) Full Newton Hessian on Gradient ($H_{fn} g$)")
create_colorbar(im3, ax=axs1[1, 1])

diff_c = h_gn_c - h_full_c
im4 = axs1[2, 0].imshow(
    diff_c.T,
    vmin=-pclip * np.abs(diff_c).max(),
    vmax=pclip * np.abs(diff_c).max(),
    **opts,
)
axs1[2, 0].set_title("5) Difference ($H_{gn} g - H_{fn} g$)")
create_colorbar(im4, ax=axs1[2, 0])

axs1[2, 1].axis("off")

for ax in axs1.flat:
    despine(ax)

fig1.tight_layout()

# %%
# Visualizing Curvelet Coefficients
# ---------------------------------
# Before visualizing the coefficients, let's take a look at the isolated Point Spread Function
# (a single point scatterer from the Gauss-Newton Hessian action) that we will transform.
# We crop a 64x64 window, precisely matching the patch size we will use for our local filter later.

ix, iz = map(int, np.unravel_index(np.argmax(dm_c), dm_c.shape))

nwin = (64, 64)
rx, rz = nwin[0] // 2, nwin[1] // 2
h_gn_zoom = np.zeros(nwin)

start_x, end_x = max(0, ix - rx), min(h_gn_c.shape[0], ix + rx)
start_z, end_z = max(0, iz - rz), min(h_gn_c.shape[1], iz + rz)
px, pz = rx - (ix - start_x), rz - (iz - start_z)

h_gn_zoom[px : px + (end_x - start_x), pz : pz + (end_z - start_z)] = h_gn_c[
    start_x:end_x, start_z:end_z
]

# Apply a Gaussian taper to isolate the single scatterer from its neighbors
x, z = np.ogrid[: nwin[0], : nwin[1]]
mask = np.exp(-((x - rx) ** 2 + (z - rz) ** 2) / (2 * 10**2))
h_gn_zoom *= mask

# Initialize the Curvelet Transform for the patch size
C_patch = UDCT(shape=nwin, num_scales=4, wedges_per_direction=3)
coeffs_patch = C_patch.forward(h_gn_zoom)

fig_psf, ax_psf = plt.subplots(1, 1, figsize=(4, 4))
im_psf = ax_psf.imshow(
    h_gn_zoom.T,
    vmin=-pclip * np.abs(h_gn_zoom).max(),
    vmax=pclip * np.abs(h_gn_zoom).max(),
    cmap="RdBu_r",
    aspect="equal",
)
ax_psf.set_title("Zoomed Isolated Scatterer (PSF)")
create_colorbar(im_psf, ax=ax_psf)
despine(ax_psf)
fig_psf.tight_layout()

#
# %%
# Let's visualize its curvelet coefficients at scale 2 (a mid-frequency scale)
scale_idx = 2

num_dirs = len(coeffs_patch[scale_idx])
num_wedges = len(coeffs_patch[scale_idx][0])

fig, axs = plt.subplots(num_dirs, num_wedges, figsize=(3 * num_wedges, 3 * num_dirs))
fig.suptitle(
    f"Curvelet Coefficients of Hessian Action (Scale {scale_idx})", fontsize=14
)

vmax_coeff = max(
    np.abs(coeffs_patch[scale_idx][d][w]).max()
    for d in range(num_dirs)
    for w in range(num_wedges)
)

for d in range(num_dirs):
    for w in range(num_wedges):
        ax = axs[d, w]
        coeff_real = np.real(coeffs_patch[scale_idx][d][w])
        im = ax.imshow(
            coeff_real.T,
            vmin=-vmax_coeff,
            vmax=vmax_coeff,
            cmap="RdBu_r",
            aspect="equal",
            extent=[0, 1, 1, 0],
        )
        ax.set_title(f"Dir {d}, Wedge {w}")
        ax.set_xticks([])
        ax.set_yticks([])
        despine(ax)

fig.tight_layout()

# %%
# Estimating the Curvelet-Domain Hessian Filter (CHF)
# ---------------------------------------------------
# By applying the curvelet-domain inverse filter in sliding windows, we can estimate :math:`H^{-1}` and
# recover the true grid of scatterers from the blurred Hessian-vector product.
#
# **Why Patching?** Although the curvelet transform provides both scale and directional
# localization, applying it to the entire image acts as a stationary filter. In reality,
# the Hessian is highly spatially varying (non-stationary) due to local illumination
# differences. Operating on local patches allows the filter to adapt to these
# spatial variations while still exploiting the directional localization of curvelets.

# Define sliding window parameters
nover = (32, 32)
dimsd = grad.shape

# Use PyLops to design the patch geometry
nwins, dims, mwins, dwins = pylops.signalprocessing.patch2d_design(
    dimsd, nwin, nover, nwin
)

# Initialize the Patch2D operator with an Identity inner operator.
# The adjoint (.H) extracts patches from an image, while the forward
# operator overlaps, tapers, and adds patches back into the full image.
P = pylops.signalprocessing.Patch2D(
    pylops.Identity(int(np.prod(nwin))),
    dims,
    dimsd,
    nwin,
    nover,
    nop=nwin,
    tapertype="hanning",
)

# Extract patches using the adjoint of the Patch2D operator
patches_grad = (P.H * grad.ravel()).reshape((nwins[0], nwins[1], nwin[0], nwin[1]))
patches_h_gn = (P.H * h_gn.ravel()).reshape((nwins[0], nwins[1], nwin[0], nwin[1]))
patches_h_full = (P.H * h_full.ravel()).reshape((nwins[0], nwins[1], nwin[0], nwin[1]))

patches_est = np.zeros_like(patches_grad)
patches_est_full = np.zeros_like(patches_grad)

for i in range(nwins[0]):
    for j in range(nwins[1]):
        patch_grad = patches_grad[i, j]
        patch_h_gn = patches_h_gn[i, j]
        patch_h_full = patches_h_full[i, j]

        # Forward Curvelet Transform of the patch
        coeffs_grad_patch = C_patch.forward(patch_grad)
        coeffs_h_gn_patch = C_patch.forward(patch_h_gn)
        coeffs_h_full_patch = C_patch.forward(patch_h_full)

        # Compute global max for stabilization across the entire patch
        # This prevents amplifying noise in wedges that are in the null space
        max_h_gn = max(
            np.max(np.abs(coeffs_h_gn_patch[s][d][w]))
            for s in range(len(coeffs_h_gn_patch))
            for d in range(len(coeffs_h_gn_patch[s]))
            for w in range(len(coeffs_h_gn_patch[s][d]))
        )

        max_h_full = max(
            np.max(np.abs(coeffs_h_full_patch[s][d][w]))
            for s in range(len(coeffs_h_full_patch))
            for d in range(len(coeffs_h_full_patch[s]))
            for w in range(len(coeffs_h_full_patch[s][d]))
        )

        eps_gn = 1e-8 * max_h_gn
        eps_full = 1e-8 * max_h_full

        coeffs_inv = []
        coeffs_inv_full = []
        for s in range(len(coeffs_grad_patch)):
            scale_coeffs = []
            scale_coeffs_full = []
            for d in range(len(coeffs_grad_patch[s])):
                dir_coeffs = []
                dir_coeffs_full = []
                for w in range(len(coeffs_grad_patch[s][d])):
                    # Magnitude-based estimation. Differs from Wang et al. (2017)
                    # which uses an L2 energy ratio: sqrt(|g|^2 / (|Hg|^2 + eps)).
                    # Smoothing magnitudes directly is less sensitive to extreme outliers.
                    abs_grad = np.abs(coeffs_grad_patch[s][d][w])
                    smooth_grad: np.ndarray = gaussian_filter(abs_grad, sigma=0.5)

                    # For GN
                    abs_h = np.abs(coeffs_h_gn_patch[s][d][w])
                    smooth_h: np.ndarray = gaussian_filter(abs_h, sigma=0.5)
                    filt = smooth_grad / (smooth_h + eps_gn)
                    dir_coeffs.append(coeffs_grad_patch[s][d][w] * filt)

                    # For Full Newton
                    abs_h_full = np.abs(coeffs_h_full_patch[s][d][w])
                    smooth_h_full: np.ndarray = gaussian_filter(abs_h_full, sigma=0.5)
                    filt_full = smooth_grad / (smooth_h_full + eps_full)
                    dir_coeffs_full.append(coeffs_grad_patch[s][d][w] * filt_full)

                scale_coeffs.append(dir_coeffs)
                scale_coeffs_full.append(dir_coeffs_full)
            coeffs_inv.append(scale_coeffs)
            coeffs_inv_full.append(scale_coeffs_full)

        # Inverse transform the filtered patch
        patches_est[i, j] = np.real(C_patch.backward(coeffs_inv))
        patches_est_full[i, j] = np.real(C_patch.backward(coeffs_inv_full))

# Overlap-add accumulation using the forward Patch2D operator
dm_est = (P * patches_est.ravel()).reshape(dimsd)
dm_est_full = (P * patches_est_full.ravel()).reshape(dimsd)

dm_est_c = dm_est[slice_x, slice_z]
dm_est_full_c = dm_est_full[slice_x, slice_z]

fig, axs = plt.subplots(2, 2, figsize=(10, 10))

opts = {"cmap": "RdBu_r", "aspect": "equal"}
pclip = 0.5
vmax_dm = pclip * np.abs(dm_c).max()
vmax_grad = pclip * np.abs(grad_c).max()
vmax_est = pclip * np.abs(dm_est_c).max()
vmax_est_full = pclip * np.abs(dm_est_full_c).max()

im0 = axs[0, 0].imshow(dm_c.T, vmin=-vmax_dm, vmax=vmax_dm, **opts)
axs[0, 0].set_title("1) True Scatterer ($\\delta m$)")
create_colorbar(im0, ax=axs[0, 0])

im1 = axs[0, 1].imshow(grad_c.T, vmin=-vmax_grad, vmax=vmax_grad, **opts)
axs[0, 1].set_title("2) Gradient ($g = J^\\dagger \\delta d$)")
create_colorbar(im1, ax=axs[0, 1])

im2 = axs[1, 0].imshow(dm_est_c.T, vmin=-vmax_est, vmax=vmax_est, **opts)
axs[1, 0].set_title("3) Recovered via GN CHF ($(H_{gn})^{-1} g$)")
create_colorbar(im2, ax=axs[1, 0])

im3 = axs[1, 1].imshow(dm_est_full_c.T, vmin=-vmax_est_full, vmax=vmax_est_full, **opts)
axs[1, 1].set_title("4) Recovered via Full Newton CHF ($(H_{fn})^{-1} g$)")
create_colorbar(im3, ax=axs[1, 1])

for ax in axs.flat:
    despine(ax)

fig.tight_layout()
plt.show()

# %%
# References
# ----------
#
# .. bibliography::
#    :filter: docname in docnames
